"""SQLite-first persistence for Lifted Sign (optional Postgres).

The canonical dialect is **SQLite**. Every query in the app is written in
SQLite's SQL; when (and only when) ``config.DATABASE_URL`` is set do we translate
those statements on the fly to the form psycopg3 expects and talk to Postgres
instead. Unset ``DATABASE_URL`` ⇒ a zero-config local SQLite file at
``config.DATA_DIR / "sign.db"`` (created on first use). ``psycopg`` is imported
**lazily** — a self-host SQLite install never needs it installed.

This module owns only the *shared infra* tables (``settings``, ``auth_limits``,
``auth_rate_limits``). The sign/esign tables are owned by their modules, each of
which keeps its own additive ``db._columns`` migrations:

    * ``sign_accounts``   -> sign_accounts.py
    * ``sign_api_keys``   -> sign_api_keys.py
    * ``agreements``, ``agreement_signers``, ``agreement_fields``,
      ``agreement_events``, ``esign_templates`` -> esign.py

``ensure_tables()`` creates the infra tables and then delegates to those modules
so a single call materializes every table on a blank database.

Public API: ``connect``, ``ensure_tables`` (alias ``init_db``), ``insert_returning``,
``_columns``, ``get_setting``, ``set_setting``, ``auth_limit_locked``,
``auth_limit_record``, ``auth_rate_allowed``, ``now``.
"""

from __future__ import annotations

import importlib
import json
import re
import sqlite3
import time
from typing import Any

from . import config

# psycopg is loaded lazily (see _load_psycopg) — SQLite-only installs never import it.
_psycopg = None
_psycopg_pool = None
_NumericAsFloat = None


def _use_pg() -> bool:
    """True when a Postgres DSN is configured; False ⇒ the SQLite default."""
    return bool(config.DATABASE_URL)


def now() -> float:
    return time.time()


# ---------------------------------------------------------------------------
# SQLite -> Postgres translation (canonical dialect is SQLite)
# ---------------------------------------------------------------------------


def _translate_sql(sql: str) -> str:
    """Translate SQLite-style SQL to the form psycopg3 expects.

    - `?` placeholders -> `%s`
    - literal `%` (e.g. inside LIKE patterns in the SQL text) -> `%%` so psycopg
      doesn't treat it as a parameter marker
    Both transforms skip the contents of single-quoted string literals, so a `?`
    or `%` inside `'...'` is left untouched.
    """
    out = []
    in_str = False
    i = 0
    n = len(sql)
    while i < n:
        c = sql[i]
        if c == "'":
            in_str = not in_str
            out.append(c)
            i += 1
        elif in_str:
            out.append("%%" if c == "%" else c)
            i += 1
        elif c == "%":
            out.append("%%")
            i += 1
        elif c == "?":
            out.append("%s")
            i += 1
        elif c == ":" and i + 1 < n and sql[i + 1] == ":":
            out.append("::")  # Postgres cast, not a named placeholder
            i += 2
        elif c == ":" and i + 1 < n and (sql[i + 1].isalpha() or sql[i + 1] == "_"):
            # named placeholder :name -> %(name)s  (psycopg mapping params)
            j = i + 1
            while j < n and (sql[j].isalnum() or sql[j] == "_"):
                j += 1
            out.append(f"%({sql[i + 1 : j]})s")
            i = j
        else:
            out.append(c)
            i += 1
    return "".join(out)


_DDL_AUTOINC = re.compile(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", re.IGNORECASE)
_DDL_REAL = re.compile(r"\bREAL\b", re.IGNORECASE)
_DDL_BLOB = re.compile(r"\bBLOB\b", re.IGNORECASE)


def _translate_ddl(sql: str) -> str:
    """Translate SQLite DDL types to Postgres equivalents.

    - `INTEGER PRIMARY KEY AUTOINCREMENT` -> identity column. BY DEFAULT (not ALWAYS)
      so a data migration can insert explicit ids.
    - `REAL` -> `double precision` (float4 can't hold an epoch second precisely).
    - `BLOB` -> `bytea`.
    """
    sql = _DDL_AUTOINC.sub("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    sql = _DDL_REAL.sub("double precision", sql)
    sql = _DDL_BLOB.sub("bytea", sql)
    return sql


def _is_ddl(sql: str) -> bool:
    head = sql.lstrip()[:6].upper()
    return head.startswith("CREATE") or head.startswith("ALTER")


_INSERT_OR_IGNORE = re.compile(r"^\s*INSERT\s+OR\s+IGNORE", re.IGNORECASE)
_INSERT_OR_REPLACE = re.compile(r"^\s*INSERT\s+OR\s+REPLACE", re.IGNORECASE)


def _to_pg(sql: str) -> str:
    """Full SQLite->Postgres statement rewrite used by the cursor wrapper."""
    if _INSERT_OR_IGNORE.match(sql):
        sql = _INSERT_OR_IGNORE.sub("INSERT", sql, count=1)
        if "ON CONFLICT" not in sql.upper():
            sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    elif _INSERT_OR_REPLACE.match(sql):
        # No generic translation (needs a conflict target); rewrite the few call
        # sites as explicit upserts. Fail loudly if one is missed.
        raise NotImplementedError(
            "INSERT OR REPLACE must be rewritten as an explicit upsert for Postgres"
        )
    if _is_ddl(sql):
        sql = _translate_ddl(sql)
    return _translate_sql(sql)


# ---------------------------------------------------------------------------
# Hybrid row (sqlite3.Row work-alike for the Postgres branch)
# ---------------------------------------------------------------------------


class _Row:
    """sqlite3.Row work-alike: supports row[0] and row['col'], plus .keys()/.get()."""

    __slots__ = ("_cols", "_vals", "_map")

    def __init__(self, cols, vals):
        self._cols = cols
        self._vals = vals
        self._map = {c: i for i, c in enumerate(cols)}

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._vals[key]
        return self._vals[self._map[key]]

    def get(self, key, default=None):
        i = self._map.get(key)
        return self._vals[i] if i is not None else default

    def keys(self):
        return list(self._cols)

    def __iter__(self):
        return iter(self._vals)

    def __contains__(self, key):
        return key in self._map

    def __len__(self):
        return len(self._vals)


def _hybrid_row(cursor):
    desc = cursor.description
    cols = [d.name for d in desc] if desc else []

    def make(values):
        return _Row(cols, values)

    return make


# ---------------------------------------------------------------------------
# Postgres cursor/connection shims (sqlite3 work-alikes backed by psycopg)
# ---------------------------------------------------------------------------


class PgCursor:
    """Wraps a psycopg cursor to accept sqlite-style SQL (`?` params, sqlite DDL)."""

    def __init__(self, raw):
        self._c = raw

    def execute(self, sql, params=()):
        # SQLite transaction control (e.g. "BEGIN IMMEDIATE") is a no-op here:
        # psycopg manages the transaction (autocommit=False) and commits via .commit().
        if sql.lstrip().split(None, 1)[0].upper() == "BEGIN":
            return self
        if isinstance(params, dict):
            p = params  # named (:name -> %(name)s) params pass through as a mapping
        else:
            p = tuple(params) if params else None
        self._c.execute(_to_pg(sql), p)
        return self

    def executemany(self, sql, seq):
        self._c.executemany(
            _to_pg(sql),
            [p if isinstance(p, dict) else tuple(p) for p in seq],
        )
        return self

    def fetchone(self):
        return self._c.fetchone()

    def fetchall(self):
        return self._c.fetchall()

    def __iter__(self):
        return iter(self._c)

    @property
    def rowcount(self):
        return self._c.rowcount

    @property
    def description(self):
        return self._c.description

    @property
    def lastrowid(self):
        # FRAGILE emulation — PREFER insert_returning(conn, sql, params) for any NEW
        # insert that needs the generated id. lastval() returns the last sequence value
        # touched in THIS session, correct only if the immediately-preceding statement
        # was an INSERT that advanced exactly one identity sequence. insert_returning
        # appends `RETURNING id` (unambiguous on PG, real lastrowid on SQLite).
        self._c.execute("SELECT lastval()")
        return self._c.fetchone()[0]


class PgConnection:
    """sqlite3.Connection work-alike backed by psycopg, used app-wide via connect().

    When created from the pool (`pool` set), close() returns the underlying
    connection to the pool instead of tearing down the socket. When pooling is
    unavailable, `pool` is None and close() closes the socket.
    """

    def __init__(self, raw, pool=None):
        self._raw = raw
        self._pool = pool

    def cursor(self):
        return PgCursor(self._raw.cursor())

    def execute(self, sql, params=()):
        cur = self.cursor()
        cur.execute(sql, params)
        return cur

    def executescript(self, sql):
        # psycopg runs a multi-statement string in one execute() (no params).
        self._raw.execute(_translate_ddl(sql) if _is_ddl(sql) else sql)

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        pool = self._pool
        if pool is None:
            self._raw.close()
            return
        # Return to the pool. Roll back any open/aborted transaction first so a
        # pooled connection is never handed out mid-transaction.
        raw = self._raw
        self._raw = None
        self._pool = None
        try:
            raw.rollback()
        except Exception:
            pass
        try:
            pool.putconn(raw)
        except Exception:
            try:
                raw.close()
            except Exception:
                pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is None:
            self._raw.commit()
        else:
            self._raw.rollback()
        return False


def _load_psycopg():
    """Import psycopg (and, if present, psycopg_pool) once, on first Postgres use.

    Builds the numeric->float loader class after psycopg is available. Raises a
    clear error if DATABASE_URL is set but psycopg isn't installed.
    """
    global _psycopg, _psycopg_pool, _NumericAsFloat
    if _psycopg is not None:
        return _psycopg
    try:
        import psycopg
    except ImportError as e:  # pragma: no cover - only hit when PG is requested
        raise RuntimeError(
            "DATABASE_URL is set but psycopg is not installed. "
            "Install it with `pip install 'psycopg[binary,pool]'` or unset "
            "DATABASE_URL to use the default SQLite backend."
        ) from e
    _psycopg = psycopg
    try:  # optional connection pool (perf: avoids per-call TCP+TLS+auth handshake)
        import psycopg_pool

        _psycopg_pool = psycopg_pool
    except ImportError:  # pragma: no cover - pool absent -> connect-per-call
        _psycopg_pool = None

    from psycopg.adapt import Loader

    class _NumericLoader(Loader):
        """Return Postgres numeric as float (matches SQLite, keeps values JSON-safe)."""

        def load(self, data):
            if data is None:
                return None
            return float(bytes(data) if not isinstance(data, (str, bytes)) else data)

    _NumericAsFloat = _NumericLoader
    return _psycopg


_PG_POOL = None
_PG_POOL_DSN: str | None = None


def _configure_pg(raw) -> None:
    """Per-connection setup applied once when the pool opens a connection."""
    raw.autocommit = False
    raw.row_factory = _hybrid_row
    raw.adapters.register_loader("numeric", _NumericAsFloat)


def _pg_pool():
    """Lazily build (once) a module-level connection pool for the current DSN.

    Returns None when pooling is unavailable (psycopg_pool not installed) — callers
    then fall back to a direct psycopg.connect(). Keyed on the DSN so a runtime DSN
    change rebuilds it.
    """
    global _PG_POOL, _PG_POOL_DSN
    dsn = config.DATABASE_URL
    if _psycopg_pool is None:
        return None
    if _PG_POOL is not None and _PG_POOL_DSN == dsn:
        return _PG_POOL
    if _PG_POOL is not None:  # DSN changed — drop the old pool
        try:
            _PG_POOL.close()
        except Exception:
            pass
        _PG_POOL = None
    try:
        _PG_POOL = _psycopg_pool.ConnectionPool(
            conninfo=dsn,
            min_size=2,
            max_size=12,
            timeout=10.0,
            max_idle=300.0,
            configure=_configure_pg,
            kwargs={"row_factory": _hybrid_row},
            open=True,
        )
        _PG_POOL_DSN = dsn
    except Exception:
        # If the pool can't be built for any reason, degrade to connect-per-call.
        _PG_POOL = None
        return None
    return _PG_POOL


def connect():
    """Open a connection to the configured backend.

    Postgres (``config.DATABASE_URL`` set): a pooled psycopg connection when
    psycopg_pool is available, else a fresh psycopg.connect(). SQLite (default):
    a WAL-mode local file at ``config.DATA_DIR / "sign.db"`` (dir created on demand).
    """
    if _use_pg():
        _load_psycopg()
        pool = _pg_pool()
        if pool is not None:
            raw = pool.getconn()
            return PgConnection(raw, pool=pool)
        raw = _psycopg.connect(config.DATABASE_URL, autocommit=False, row_factory=_hybrid_row)
        raw.adapters.register_loader("numeric", _NumericAsFloat)
        return PgConnection(raw)
    config.DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(config.DATA_DIR / "sign.db", timeout=10.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def insert_returning(conn, sql: str, params=()) -> int:
    """INSERT and return the new `id` (replaces sqlite cursor.lastrowid on Postgres).

    On Postgres it appends RETURNING id; on SQLite it falls back to cursor.lastrowid.
    """
    if _use_pg():
        cur = conn.execute(sql.rstrip().rstrip(";") + " RETURNING id", params)
        return int(cur.fetchone()["id"])
    cur = conn.execute(sql, params)
    return int(cur.lastrowid)


def _columns(conn, table: str) -> list[str]:
    """Existing column names for a table, on either backend.

    Used by the sign modules for additive migrations. NEVER a raw PRAGMA — that is
    a syntax error on Postgres; this branches on the backend.
    """
    if _use_pg():
        rows = conn.execute(
            "SELECT column_name AS name FROM information_schema.columns WHERE table_name=?",
            (table,),
        ).fetchall()
    else:
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return [r["name"] for r in rows]


# ---------------------------------------------------------------------------
# Schema — shared infra tables only. Sign/esign tables are owned by their
# modules (sign_accounts.py, sign_api_keys.py, esign.py) and created by their
# own ensure_tables(), which ensure_tables() below delegates to.
# ---------------------------------------------------------------------------

SCHEMA = """
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_limits (
    key        TEXT PRIMARY KEY,
    fails      INTEGER NOT NULL DEFAULT 0,
    lock_until REAL NOT NULL DEFAULT 0,
    updated_at REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_rate_limits (
    key          TEXT PRIMARY KEY,
    count        INTEGER NOT NULL DEFAULT 0,
    window_start REAL NOT NULL,
    updated_at   REAL NOT NULL
);
"""

# Modules that own sign/esign tables; each has an idempotent ensure_tables().
# Order: accounts before esign (esign rows reference an owner account id) before keys.
_SIGN_TABLE_MODULES = ("sign_accounts", "esign", "sign_api_keys")

_MIGRATE_LOCK_KEY = 729105  # fixed key for the cross-container schema-migration lock (PG-only)


def ensure_tables() -> None:
    """Create every Lifted Sign table on a blank database (idempotent).

    Creates the infra tables (settings, auth_limits, auth_rate_limits) then defers
    to each sign module's ensure_tables() for the agreements/signers/fields/events/
    templates and account/api-key tables (which carry their own additive migrations).
    """
    conn = connect()
    locked = False
    try:
        # Serialize migration across processes on Postgres (web + worker share one DB
        # and both call this at boot; concurrent CREATE/ALTER on the same object can
        # deadlock). A session advisory lock lets one migrate; others wait then find
        # the idempotent migration already applied. SQLite dev is single-process.
        if _use_pg():
            try:
                conn.execute(f"SELECT pg_advisory_lock({_MIGRATE_LOCK_KEY})")
                locked = True
            except Exception:
                pass  # never let lock acquisition block boot
        conn.executescript(SCHEMA)
        conn.commit()
    finally:
        if locked:
            try:
                conn.execute(f"SELECT pg_advisory_unlock({_MIGRATE_LOCK_KEY})")
            except Exception:
                pass
        conn.close()
    # Deferred import (these modules do `from . import db`, so a top-level import here
    # would be circular). Each ensure_tables() is idempotent.
    for modname in _SIGN_TABLE_MODULES:
        try:
            mod = importlib.import_module(f".{modname}", __package__)
        except ImportError:
            continue  # module not present in this build — skip its tables
        ensure = getattr(mod, "ensure_tables", None)
        if callable(ensure):
            ensure()


# Back-compat alias for call sites that used the original name.
init_db = ensure_tables


# ---------------------------------------------------------------------------
# Settings (key/value; JSON-encoded values)
# ---------------------------------------------------------------------------


def get_setting(key: str, default: Any = None) -> Any:
    conn = connect()
    try:
        row = conn.execute("SELECT value FROM settings WHERE key=?", (key,)).fetchone()
        if not row:
            return default
        try:
            return json.loads(row["value"])
        except (json.JSONDecodeError, TypeError):
            return row["value"]
    finally:
        conn.close()


def set_setting(key: str, value: Any) -> None:
    conn = connect()
    try:
        conn.execute(
            "INSERT INTO settings(key,value) VALUES(?,?) "
            "ON CONFLICT(key) DO UPDATE SET value=excluded.value",
            (key, json.dumps(value)),
        )
        conn.commit()
    finally:
        conn.close()


def claim_once(key: str, value: Any = None) -> bool:
    """Atomically claim a one-time marker. Returns True the first time ``key`` is claimed and
    False on every subsequent call — the ``settings`` primary key makes the INSERT-if-absent
    race-safe (``ON CONFLICT DO NOTHING`` touches no row on a repeat), so two concurrent callers
    can never both win. Used to make single-use tokens (magic-link, email-verify) genuinely
    one-time. The caller stores an expiry in ``value`` and is responsible for pruning."""
    conn = connect()
    try:
        cur = conn.execute(
            "INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO NOTHING",
            (key, json.dumps(value)),
        )
        conn.commit()
        return cur.rowcount == 1
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Auth throttling — brute-force lockout (auth_limits) + fixed-window rate
# limiting (auth_rate_limits). Both do their read-modify-write atomically in a
# single upsert with RETURNING so counters stay correct on Postgres under READ
# COMMITTED; BEGIN IMMEDIATE is a real write lock on SQLite and a no-op on PG.
# ---------------------------------------------------------------------------


def auth_limit_locked(key: str) -> bool:
    conn = connect()
    try:
        row = conn.execute("SELECT lock_until FROM auth_limits WHERE key=?", (key,)).fetchone()
        return bool(row and now() < float(row["lock_until"] or 0))
    finally:
        conn.close()


def auth_limit_record(key: str, ok: bool, fail_limit: int, lock_seconds: int) -> None:
    ts = now()
    conn = connect()
    try:
        conn.execute("BEGIN IMMEDIATE")
        if ok:
            conn.execute("DELETE FROM auth_limits WHERE key=?", (key,))
            conn.commit()
            return
        # Atomically increment fails, BUT do not increment while currently locked
        # (preserve "already locked within the window" behavior). RETURNING gives the
        # post-write fails/lock_until under the row lock.
        cur = conn.execute(
            "INSERT INTO auth_limits(key,fails,lock_until,updated_at) VALUES(?,1,0,?) "
            "ON CONFLICT(key) DO UPDATE SET "
            "  fails = CASE WHEN ? < auth_limits.lock_until "
            "               THEN auth_limits.fails ELSE auth_limits.fails + 1 END,"
            "  lock_until = CASE WHEN ? < auth_limits.lock_until "
            "                    THEN auth_limits.lock_until ELSE 0 END,"
            "  updated_at = ? "
            "RETURNING fails, lock_until",
            (key, ts, ts, ts, ts),
        )
        row = cur.fetchone()
        fails = int(row["fails"] or 0)
        lock_until = float(row["lock_until"] or 0)
        # If already locked (and still within the window), leave the lock as-is.
        # Otherwise, once failures reach the limit, set the lock window and reset.
        if ts < lock_until:
            conn.commit()
            return
        if fails >= fail_limit:
            conn.execute(
                "UPDATE auth_limits SET fails=0, lock_until=?, updated_at=? WHERE key=?",
                (ts + lock_seconds, ts, key),
            )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def auth_rate_allowed(key: str, limit: int, window_seconds: int) -> bool:
    ts = now()
    conn = connect()
    try:
        conn.execute("BEGIN IMMEDIATE")
        cur = conn.execute(
            "INSERT INTO auth_rate_limits(key,count,window_start,updated_at) "
            "VALUES(?,1,?,?) "
            "ON CONFLICT(key) DO UPDATE SET "
            "  count = CASE WHEN ?-auth_rate_limits.window_start >= ? "
            "               THEN 1 ELSE auth_rate_limits.count + 1 END,"
            "  window_start = CASE WHEN ?-auth_rate_limits.window_start >= ? "
            "                      THEN ? ELSE auth_rate_limits.window_start END,"
            "  updated_at = ? "
            "RETURNING count",
            (key, ts, ts, ts, window_seconds, ts, window_seconds, ts, ts),
        )
        new_count = int(cur.fetchone()["count"] or 0)
        conn.commit()
        return new_count <= limit
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
