"""Pure SQLite→Postgres dialect translation + the hybrid-row shim.

The canonical dialect is SQLite; the Postgres backend rewrites statements on the fly. These pure
string transforms and the ``_Row`` work-alike are unit-testable without a live Postgres, and they
gate correctness for every estate deployment that flips ``DATABASE_URL`` on.
"""

from __future__ import annotations

import pytest


def test_translate_placeholders_and_percent():
    from sign import db

    assert db._translate_sql("SELECT * FROM t WHERE id=?") == "SELECT * FROM t WHERE id=%s"
    # a literal % is doubled so psycopg doesn't read it as a marker (psycopg's % parsing
    # ignores SQL string quoting, so a % inside '...' is doubled too)
    assert db._translate_sql("x % y") == "x %% y"
    assert db._translate_sql("WHERE c LIKE 'a?b%'") == "WHERE c LIKE 'a?b%%'"
    # a ? inside a single-quoted literal is left untouched (not turned into a placeholder)
    assert db._translate_sql("WHERE c = 'a?b'") == "WHERE c = 'a?b'"


def test_translate_casts_and_named_params():
    from sign import db

    assert "::" in db._translate_sql("SELECT x::int FROM t")
    assert db._translate_sql("WHERE k=:name") == "WHERE k=%(name)s"


def test_translate_ddl_types():
    from sign import db

    out = db._translate_ddl(
        "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, ts REAL, blob BLOB)"
    )
    assert "GENERATED BY DEFAULT AS IDENTITY" in out
    assert "double precision" in out
    assert "bytea" in out


def test_is_ddl_detection():
    from sign import db

    assert db._is_ddl("CREATE TABLE x (a int)") is True
    assert db._is_ddl("  ALTER TABLE x ADD COLUMN y int") is True
    assert db._is_ddl("SELECT 1") is False


def test_to_pg_insert_or_ignore_and_replace():
    from sign import db

    got = db._to_pg("INSERT OR IGNORE INTO t(a) VALUES(?)")
    assert got.startswith("INSERT INTO t")
    assert "ON CONFLICT DO NOTHING" in got
    with pytest.raises(NotImplementedError):
        db._to_pg("INSERT OR REPLACE INTO t(a) VALUES(?)")


def test_hybrid_row_dual_access():
    from sign import db

    row = db._Row(["id", "name"], [7, "Ada"])
    assert row[0] == 7
    assert row["name"] == "Ada"
    assert row.get("missing", "d") == "d"
    assert list(row.keys()) == ["id", "name"]
    assert "id" in row and len(row) == 2
    assert list(iter(row)) == [7, "Ada"]
